[profile.default]
libs = ['lib']
out = 'out'
src = 'src'

[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"
zk-rpc = "${ZKSYNC_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
